name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build and test
        run: ./gradlew runDebugExecutableMacosX64

  linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build and test
        run: ./gradlew runDebugExecutableLinuxX64

  mingw:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build and test
        run: ./gradlew runDebugExecutableMingwX64

